package ru.Ablazzing.lesson8_Exceptions;

public class Main {
    public static void main(String[] args) throws MyFirstException {
        int a = 10;
        int b = 0;
//        try {
//            if (b == 0) {
//                throw new MyFirstException("Деление на 0");
//            }
//            System.out.println(a / b);
//        } catch (MyFirstException e) {
//            System.out.println("Делить на 0, нельзя!");
//            System.out.println(MyFirstException.countException);
//        }

//        if (b == 0) {
//            throw new MyFirstException("Exception");
//        }

//        if (a == 10) {
//            throw new RuntimeException("a = 10");
//        }

//        Integer integer = Calc.add(1, 0);
//        System.out.println("Идём дальше.");
    }
}
